### ISSUE TITLE
Cannot load UV file ???

### ISSUE THREAD

**Issue by Azagwen** [jmc2obj/j-mc-2-obj#138]
I tried exporting a world but it gave me the following error message :

>Cannot Load UV file !
>SAXParseException : Content is not allowed in Prolog.

With the following Console Log

`
Using file to recalculate UVs: G:\Draws\Projects_3D\Projects_Blender\Minecraft
ERROR: Cannot load UV file!
org.xml.sax.SAXParseException; systemId: file:/G:/Draws/Projects_3D/Projects_Blender/Minecraft/; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at org.jmc.util.Xml.loadDocument(Xml.java:40)
	at org.jmc.UVRecalculate.load(UVRecalculate.java:28)
	at org.jmc.ObjExporter.export(ObjExporter.java:110)
	at org.jmc.gui.ExportWindow$10$2.run(ExportWindow.java:869)
	at java.lang.Thread.run(Unknown Source)
`

I have absolutely no idea what this means, the Wiki page referenced on the site is closed.
is that normal ? If it is, what did I do wrong ?

Edit : it did create a OBJ file but it was completely Empty

**Comment by mmdanggg2** [comment]
This happened because you didn't select the .uv file that is generated when you export the textures to a single file.
The latest version makes this clearer.
