### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by TheStrangePototo** [jmc2obj/j-mc-2-obj#139]
Armor stands don't import. The only error I have in my console is `ERROR: Cannot check update 
java.io.FileNotFoundException: https://www.jmc2obj.net/downloads/update.xml
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at org.jmc.util.Xml.loadDocument(Xml.java:54)
	at org.jmc.CheckUpdate.isAvailable(CheckUpdate.java:45)
	at org.jmc.CheckUpdate$1.run(CheckUpdate.java:24)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by mmdanggg2** [comment]
You must have a very old version, latest ones don't check that url for updates. Please update and try it again.
