### ISSUE TITLE
Paintings cause export to crash

### ISSUE THREAD

**Issue by Macintosh-Fan** [jmc2obj/j-mc-2-obj#206]
I get this error when exporting a world.
```
Error rendering entity minecraft:painting, skipping.
java.lang.NullPointerException: Cannot read field "value" because the return value of "org.jmc.NBT.TAG_Compound.getElement(String)" is null
	at org.jmc.entities.Painting.addEntity(Painting.java:68)
	at org.jmc.threading.ChunkProcessor.process(ChunkProcessor.java:246)
	at org.jmc.threading.ReaderRunnable.exportChunk(ReaderRunnable.java:63)
	at org.jmc.threading.ReaderRunnable.run(ReaderRunnable.java:42)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by Macintosh-Fan** [comment]
It seems like the problem is when there are paintings in the scene, which is an entity.
