### ISSUE TITLE
No Steve entity texture?

### ISSUE THREAD

**Issue by Macintosh-Fan** [jmc2obj/j-mc-2-obj#210]
```
ERROR: Couldn't export texture minecraft:entity/steve
java.io.FileNotFoundException: Couldn't find assets/minecraft/textures/entity/steve.png in current resource packs
	at org.jmc.util.ResourcePackIO.loadResource(ResourcePackIO.java:71)
	at org.jmc.util.ResourcePackIO.loadResourceAsStream(ResourcePackIO.java:43)
	at org.jmc.util.ResourcePackIO.loadImage(ResourcePackIO.java:26)
	at org.jmc.registry.TextureEntry.getImage(TextureEntry.java:109)
	at org.jmc.TextureExporter.exportTextures(TextureExporter.java:159)
	at org.jmc.ObjExporter.export(ObjExporter.java:382)
	at org.jmc.gui.ExportWindow$8$1$1.run(ExportWindow.java:748)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by mmdanggg2** [comment]
Not sure why that's happening, steve.png should be there in a 1.19 minecraft
![image](https://user-images.githubusercontent.com/3161587/215628234-768ca4b9-c208-44ae-992a-684d673435d7.png)

**Comment by Macintosh-Fan** [comment]
Maybe for more context, but the world was originally a 1.12.2 world, just like in #209, but I opened it in 1.19.3 and used the [Chunk-Pregenerator](https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator), but it might not be working properly. Anyways, I'll close the issue as it's likely just a bit of a corrupted world.
