### ISSUE TITLE
Fresh Download, issue with paths

### ISSUE THREAD

**Issue by kaweepatinn1** [jmc2obj/j-mc-2-obj#231]
Console error:

ERROR: Couldn't find blockstate minecraft:grass_path in any resource pack!

**Comment by mmdanggg2** [comment]
Are you exporting a world from before 1.17? They changed the block id from grass_path to dirt_path, you will need to add the 1.16.jar file (usually in `.minecraft/versions/1.16.5/`) to your resource packs list in settings for that to export correctly.

**Comment by kaweepatinn1** [comment]
using this gave me a lot of banner base errors instead of the paths. Seems like armor stands apparently aren't working too?

**Comment by kaweepatinn1** [comment]
Tried it again, looks like everything but the armor stand works fine (it is skipped)

ERROR: Error rendering entity minecraft:armor_stand, skipping.
java.lang.StringIndexOutOfBoundsException: Range [10, -1) out of bounds for length 16
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4589)
	at java.base/java.lang.String.substring(String.java:2703)
	at org.jmc.entities.ArmorStand.addEntity(ArmorStand.java:82)
	at org.jmc.threading.ChunkProcessor.process(ChunkProcessor.java:275)
	at org.jmc.threading.ReaderRunnable.exportChunk(ReaderRunnable.java:63)
	at org.jmc.threading.ReaderRunnable.run(ReaderRunnable.java:42)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mmdanggg2** [comment]
Armor stand errors should be fixed in the next release, see #234
