### ISSUE TITLE
getSectionBlocks ignores chunkVer? Minestom export issue

### ISSUE THREAD

**Issue by AntonIXO** [jmc2obj/j-mc-2-obj#262]
Hello,
Having issues with Minestom world exports after updating to 1.21
There is two worlds, 1.20 exports succesfully, 1.21 not.
[minestom.zip](https://github.com/user-attachments/files/16159688/minestom.zip)
I added debug to investigate issue
![image](https://github.com/jmc2obj/j-mc-2-obj/assets/25568560/a85be179-10bc-45dc-93e7-c4691f1936a4)
Error:
```
Processing chunks...
Chunk DataVersion: 3953
old block format
new biome format
Chunk DataVersion: 3953
old block format
new biome format
Chunk DataVersion: 3953
Exception in thread "ReadThread-0" java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 2
        at org.jmc.Chunk$SectionBlocks.fillBlocks(Chunk.java:519)
        at org.jmc.Chunk.getSectionBlocks(Chunk.java:403)
        at org.jmc.Chunk.access$100(Chunk.java:29)
        at org.jmc.Chunk$BlocksSections$1.make(Chunk.java:213)
        at org.jmc.Chunk$BlocksSections$1.make(Chunk.java:210)
        at org.jmc.util.CachedGetter.get(CachedGetter.java:61)
        at org.jmc.Chunk$BlocksSections.getBlockData(Chunk.java:221)
        at org.jmc.threading.ThreadChunkDeligate.getBlockData(ThreadChunkDeligate.java:88)
        at org.jmc.threading.ChunkProcessor.process(ChunkProcessor.java:193)
        at org.jmc.threading.ReaderRunnable.exportChunk(ReaderRunnable.java:57)
        at org.jmc.threading.ReaderRunnable.run(ReaderRunnable.java:36)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```
Code call fillBlocks instead fillBiomes ignoring DataVersion?
But DataVersion value is ok and reads fine:
![image](https://github.com/jmc2obj/j-mc-2-obj/assets/25568560/bcf5e0eb-570f-42ea-a2b8-d296c41ce070)

**Comment by mmdanggg2** [comment]
It's reading the version just fine and correctly calling both fillBlocks and fillBiomes.
Your error here is because the `data` long array is only 64 elements long and not in the standard format which requres at minimum 256 elements. I think I see what they've done, they're trying to reduce the file size by removing the 4 bit palette index limit but that's not standard.

**Comment by AntonIXO** [comment]
So should I fix this in Minestom or you could add workaround for this?

**Comment by mmdanggg2** [comment]
I'm not gonna work around that one I'm afraid. Minecraft won't even load those chunks, the 1.20 ones at least got loaded (albeit on top of eachother at 0,0 due to the missing x,z tags as I mentioned previously)
