### ISSUE TITLE
Patrix resource pack does not work

### ISSUE THREAD

**Issue by Macintosh-Fan** [jmc2obj/j-mc-2-obj#270]
I get this error when I add the Patrix resource packs (basic, addon, items, mobs).
```
Sorting OBJ file...
Writing materials to /Users/arcadikonoval/Downloads/minecraft.mtl...
ERROR: Error while exporting OBJ:
java.lang.ClassCastException: class [B cannot be cast to class [I ([B and [I are in module java.base of loader 'bootstrap')
	at java.desktop/sun.awt.image.IntegerInterleavedRaster.setDataElements(IntegerInterleavedRaster.java:421)
	at java.desktop/java.awt.image.BufferedImage.copyData(BufferedImage.java:1495)
	at org.jmc.registry.TextureEntry.cropAnimation(TextureEntry.java:154)
	at org.jmc.registry.TextureEntry.getImage(TextureEntry.java:110)
	at org.jmc.registry.TextureEntry.hasAlpha(TextureEntry.java:87)
	at org.jmc.Materials.writeMTLFile(Materials.java:55)
	at org.jmc.ObjExporter.export(ObjExporter.java:375)
	at org.jmc.gui.ExportWindow.lambda$runExport$0(ExportWindow.java:886)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
Texture pack: https://www.patreon.com/posts/update-67-101332748

**Comment by Macintosh-Fan** [comment]
Mostly. Ignoring the connected-texture message, the leaves still seem to have a bit of a funny colour...

I did set the textures to be in the exact order as is in-game:
<img width="500" height="359" alt="Image" src="https://github.com/user-attachments/assets/95c99308-cb32-4f8a-bf49-0e584c5d22d0" />
Export settings:
<img width="539" height="588" alt="Image" src="https://github.com/user-attachments/assets/30be26fb-ddd5-4441-802a-5514d1ced720" />

Render differences:
<img width="394" height="294" alt="In-game texture" src="https://github.com/user-attachments/assets/bc4fbad0-b059-493e-83a7-2b999c8b63e4" />
![Blender render](https://github.com/user-attachments/assets/5838df86-dbdc-4a4e-9165-5752398687b3)

**Comment by Macintosh-Fan** [comment]
<img width="664" height="473" alt="Image" src="https://github.com/user-attachments/assets/0c09f3f2-e8fa-43d2-a817-f8807d7793b6" />

@mmdanggg2, it looks like it is mixing up regular and depth (or whatever it is called) textures? You can download the textures here: https://www.patreon.com/posts/update-79-132414489.

**Comment by mmdanggg2** [comment]
These look white because the biome tint hasn't been applied to them. jmc doesn't really deal with biome tints well, they are just applied per texture based on the `textures.json` config file. 
So for eg. just add this for the spruce leaves:
```json
    {"id": "minecraft:block/extra/spruce_leaves_extra", "tint": "80CA80"},
```

**Comment by Macintosh-Fan** [comment]
I got a new error when the selected region has fire. Removing the fire fixes the issue.
<img width="599" height="452" alt="Image" src="https://github.com/user-attachments/assets/01d735b3-66eb-4f16-b347-a30e099d15c4" />
```
Sorting OBJ file...
Writing materials to /Users/MY_USERNAME/Downloads/minecraft.mtl...
Exporting textures...
Couldn't export normal texture for 'minecraft:block/extra/large_fern_bottom_extra' error: Couldn't find assets/minecraft/textures/block/extra/large_fern_bottom_extra_n.png in current resource packs
Couldn't export specular texture for 'minecraft:block/extra/large_fern_bottom_extra' error: Couldn't find assets/minecraft/textures/block/extra/large_fern_bottom_extra_s.png in current resource packs
Couldn't export normal texture for 'minecraft:block/wheat_stage2' error: Couldn't find assets/minecraft/textures/block/wheat_stage2_n.png in current resource packs
Couldn't export specular texture for 'minecraft:block/wheat_stage2' error: Couldn't find assets/minecraft/textures/block/wheat_stage2_s.png in current resource packs
Couldn't export normal texture for 'minecraft:block/water_still' error: Couldn't find assets/minecraft/textures/block/water_still_n.png in current resource packs
Couldn't export specular texture for 'minecraft:block/water_still' error: Couldn't find assets/minecraft/textures/block/water_still_s.png in current resource packs
Couldn't export normal texture for 'minecraft:block/fire_0' error: Couldn't find assets/minecraft/textures/block/fire_0_n.png in current resource packs
Error while exporting OBJ:
java.awt.image.RasterFormatException: (y + height) is outside of Raster
	at java.desktop/sun.awt.image.ByteInterleavedRaster.createWritableChild(ByteInterleavedRaster.java:1244)
	at java.desktop/java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1203)
	at org.jmc.registry.TextureEntry.cropAnimation(TextureEntry.java:154)
	at org.jmc.registry.TextureEntry.getSpecularMap(TextureEntry.java:134)
	at org.jmc.TextureExporter.exportTextures(TextureExporter.java:184)
	at org.jmc.ObjExporter.export(ObjExporter.java:386)
	at org.jmc.gui.ExportWindow.lambda$runExport$0(ExportWindow.java:886)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
<img width="539" height="588" alt="Image" src="https://github.com/user-attachments/assets/9af1ebc6-fe1f-44a2-9bfc-4badbbbadebc" />
<img width="500" height="359" alt="Image" src="https://github.com/user-attachments/assets/0850fe3d-5af1-4702-bb1b-8d584b62e1f2" />
<img width="797" height="138" alt="Image" src="https://github.com/user-attachments/assets/7b5302fd-0d78-4bfd-8baa-e59e368a6e3b" />

**Comment by mmdanggg2** [comment]
And that's because the fire specular texture is not animated so it's trying to get from part of the texture that isn't there. While I work on a fix, you could disable exporting spec textures or remove the offending `fire_0_s.png` files from the texture pack.
